"""add idempotency_key to message table

Revision ID: f2ac16f31a9f
Revises: 8e1efd3b4c8d
Create Date: 2025-09-24 21:39:13.601390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2ac16f31a9f'
down_revision: Union[str, None] = '8e1efd3b4c8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('idempotency_key', sa.String(), nullable=True))
    op.create_index(op.f('ix_message_idempotency_key'), 'message', ['idempotency_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_idempotency_key'), table_name='message')
    op.drop_column('message', 'idempotency_key')
    # ### end Alembic commands ###
